config/routes.rb
Rails.application.routes.draw do
  resources :maps do
    collection do
      get :multi_status_edit_single
      post :multi_status_update_single
    end
  end

  resources :statuses

  resources :operations

  resources :instruments

  resources :makers

  resources :engineers

  resources :service_centers

  
  root to: 'maps#index'
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :engineer
  belongs_to :instrument
  belongs_to :operation
  belongs_to :status
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @makers = Maker.all.order(name: :asc)
    if @makers.blank?
      redirect_to new_maker_path, alert: "Setup is not completed yet. Register maker"
      return
    end
    unless Instrument.exists?
      redirect_to new_instrument_path, alert: "Setup is not completed yet. Register instruments"
      return
    end
    @service_centers = ServiceCenter.all
    if @service_centers.blank?
      redirect_to new_service_center_path, alert: "Setup is not completed yet. Register service centers"
      return
    end
    unless Engineer.exists?
      redirect_to new_engineer_path, alert: "Setup is not complted yet. Register engineers"
      return
    end
    @operations = Operation.all
    if @operations.blank?
      redirect_to new_operation_path, alert: "Setup is not completed yet. Register operatinos"
      return
    end
    unless Status.exists?
      redirect_to new_status_path, alert: "Setup is not complted yet. Register statuses"
      return
    end
    
    @maker = params[:maker_id].blank? ? @makers.first : Maker.find(params[:maker_id])
    @maps = get_maps_from_maker(@maker)
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
    @service_centers = ServiceCenter.all
    @makers = Maker.all
    @operations = Operation.all
    @statuses = Status.all
  end

  # GET /maps/1/edit
  def edit
    @service_centers = ServiceCenter.all
    @makers = Maker.all
    @operations = Operation.all
    @statuses = Status.all
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  def multi_status_edit_single
    @instrument = Instrument.find(params[:instrument_id])
    @engineer = Engineer.find(params[:engineer_id])
    @operations = Operation.all
    @statuses = Status.all
    @maps = get_maps_from_instrument(@instrument, :id)
  end
  
  def multi_status_update_single
    instrument = Instrument.find(params[:instrument][:id])
    engineer_id = params[:engineer][:id]
    status_ids = params[:status_id]
    operations = Operation.all
    
    # OPTIMIZE: 高速化が必要
    loop_index = 0
    operations.each do |operation|
      map = Map.find_by(instrument_id: instrument.id, engineer_id: engineer_id, operation_id: operation.id)
      if map.blank?
        map = Map.new(instrument_id: instrument.id, engineer_id: engineer_id, operation_id: operation.id, status_id: status_ids[loop_index])
        map.save
      else
        map.update(status_id: status_ids[loop_index])
      end
      loop_index += 1
    end 
    redirect_to action: :index, maker_id: instrument.maker.id
  end
  
  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:engineer_id, :instrument_id, :operation_id, :status_id)
    end
    
    def get_maps_from_maker(maker, attr=:name)
      result = Array.new
      instruments = maker.instruments
      instruments.each do |instrument|
        result[instrument.id] = get_maps_from_instrument(instrument)
=begin
        maps = instrument.maps.where.not(status_id: nil)
        maps.each do |map|
          result[map.instrument_id] = Array.new if result[map.instrument_id].blank?
          result[map.instrument_id][map.engineer_id] = Array.new if result[map.instrument_id][map.engineer_id].blank?
          result[map.instrument_id][map.engineer_id][map.operation_id] = map.status.attributes[attr.to_s]
        end
=end
      end
      return result
    end
    
    def get_maps_from_instrument(instrument, attr=:name)
      result = Array.new
      maps = instrument.maps.where.not(status_id: nil)
      maps.each do |map|
          result[map.engineer_id] = Array.new if result[map.engineer_id].blank?
          result[map.engineer_id][map.operation_id] = map.status.attributes[attr.to_s]
      end
      return result
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :engineer_id %><br>
    <%= f.grouped_collection_select :engineer_id, @service_centers, :engineers, :name, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :instrument_id %><br>
    <%= f.grouped_collection_select :instrument_id, @makers, :instruments, :name, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :operation_id %><br>
    <%= f.collection_select :operation_id, @operations, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.collection_select :status_id, @statuses, :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing certificate map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1 class="page-title">Certificate Map</h1>

<!--/ Maker select tab -->
<ul class="nav nav-tabs" role="tablist">
	<% @makers.each do |maker| %>
	<li<% if maker.id == @maker.id %> class="active" <% end %>>
		<%= link_to maker.name, {action: :index, maker_id: maker.id} %>
	</li>
	<% end %>
</ul>

<% @maker.instruments.each do |instrument| %>
<h4 class="map-title"><%= instrument.name %></h4>
<table class="table table-bordered table-striped table-hover map-table">
	<thead class="map-header">
		<tr>
			<th class="caption">サービスセンター</th>
			<th class="caption">エンジニア</th>
			<% @operations.each do |operation| %>
			<th><%= operation.name %></th>
			<% end %>
		</tr>
	</thead>
	
	<tbody>
		<% @service_centers.each do |service_center| %>
		<% first_row = true %>
		<% service_center.engineers.each do |engineer| %>
		<tr>
			<% if first_row %>
			<td rowspan="<%= service_center.engineers.size %>"><%= service_center.name %></td>
			<% first_row = false %>
			<% end %>
			<td class="map-data-engineer"><%= link_to engineer.name, {action: :multi_status_edit_single, instrument_id: instrument.id, engineer_id: engineer.id} %></td>
			<% @operations.each do |operation| %>
			<td class="map-data"><%= @maps[instrument.id][engineer.id][operation.id] unless @maps[instrument.id][engineer.id].blank? %></td>
			<% end %>
		</tr>
		<% end %>
		<% end %>
	</tbody>
</table>
<% end %>

<br>
<%= link_to 'New Instrument', {controller: :instruments, action: :new, maker_id: @maker.id} %>
<%#= link_to 'New Certificate Map', new_map_path %>

app/views/maps/multi_status_edit_single.html.erb
<h1><%= @engineer.name %>さんの編集ページ</h1>
<h2><%= @instrument.maker.name %></h2>
<h4 class="map_title"><%= @instrument.name %></h4>

<%= form_tag action: :multi_status_update_single do %>
<table class="table table-bordered map_table">
	<thead class="map_header">
		<tr>
			<th class="caption">Service Center</th>
			<th class="caption">Engineer</th>
			<% @operations.each do |operation| %>
			<th><%= operation.name %></th>
			<% end %>
		</tr>
	</thead>
	
	<tbody>
		<tr>
			<td><%= @engineer.service_center.name %></td>
			<td><%= @engineer.name %></td>
			<% @operations.each do |operation| %>
				<% if @maps[@engineer.id].blank? %>
					<td class="map_data"><%= select_tag 'status_id[]', options_from_collection_for_select(@statuses, :id, :name), include_blank: true %></td>
				<% else %>
					<td class="map_data"><%= select_tag 'status_id[]', options_from_collection_for_select(@statuses, :id, :name, selected: @maps[@engineer.id][operation.id]), include_blank: true %></td>
				<% end %>
			<% end %>
		</tr>
	</tbody>
</table>
<%= hidden_field :engineer, :id %>
<%= hidden_field :instrument, :id %>

<div class="actions">
	<%= submit_tag '登録する' %>
</div>
<% end %>

<br />
<%= link_to 'Back', {action: :index, maker_id: @instrument.maker.id} %>

app/views/maps/new.html.erb
<h1>New certificate map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered">
	<tr>
		<td class="certificate_table_caption">Engineer</td>
		<td><%= @map.engineer.name %></td>
	</tr>
	<tr>
		<td class="certificate_table_caption">Instrument</td>
		<td><%= @map.instrument.name %></td>
	</tr>
	<tr>
		<td class="certificate_table_caption">Operation</td>
		<td><%= @map.operation.name %></td>
	</tr>
	<tr>
		<td class="certificate_table_caption">Status</td>
		<td><%= @map.status.name unless @map.status.blank? %></td>
	</tr>
</table>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>