config/routes.rb
Rails.application.routes.draw do
  resources :maps do
    collection do
      get :multi_status_edit_single
      post :multi_status_update_single
    end
  end

  resources :statuses

  resources :operations

  resources :instruments

  resources :makers

  resources :engineers

  resources :service_centers

  
  root to: 'maps#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Certificate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-menu">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'Certificate Map', maps_path, class: "navbar-brand" %>
		</div>
		
		<div class="collapse navbar-collapse" id="navbar-collapse-menu">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to 'Maker', makers_path, role: "menu_item" %></li>
						<li><%= link_to 'Instrument', instruments_path, role: "menu_item" %></li>
						<li><%= link_to 'Service Center', service_centers_path, role: "menu_item" %></li>
						<li><%= link_to 'Engineer', engineers_path, role: "menu_item" %></li>
						<li><%= link_to 'Operation', operations_path, role: "menu_item" %></li>
						<li><%= link_to 'Status', statuses_path, role: "menu_item" %></li>
					</ul>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container -->
</nav>
<div class="container">
	<%= yield %>
</div>

</body>
</html>