config/routes.rb
Rails.application.routes.draw do
  resources :maps do
    collection do
      get :multi_status_edit_single
      post :multi_status_update_single
    end
  end

  resources :statuses

  resources :operations

  resources :instruments

  resources :makers

  resources :engineers

  resources :service_centers

  
  root to: 'maps#index'
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  has_many :maps, dependent: :destroy
  
  validates :name,
  presence: true,
  uniqueness: true
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:name)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<h1>Listing operations</h1>

<table class="table table-bordered">
  <thead>
    <tr class="certificate_table_caption">
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.name %></td>
        <td><%= link_to 'Show', operation, class: :crud_control %>
        	<%= link_to 'Edit', edit_operation_path(operation), class: :crud_control %>
        	<%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' }, class: :crud_control %>
        	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<% unless alert.blank? %>
<div id="error_explanation">
	<h2><%= alert %></h2>
</div>
<% end %>
<h1>New operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered">
	<tr>
		<td class="certificate_table_caption">Name</td>
		<td><%= @operation.name %></td>
	</tr>
</table>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>